### ISSUE TITLE
list_fba_studies throws error when model has no associated fba studies

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ProbModelSEED#3]
Request:

{"version":"1.1","method":"ProbModelSEED.list_fba_studies","id":"04267241479828954","params":[{"model":"/nconrad/models/Rhodobacter_sphaeroides_2.4.1.json_model"}]}:

Response:

{"version":"1.1","error":{"error":"Can't use an undefined value as an ARRAY reference at /disks/p3/deployment/lib/Bio/ModelSEED/ProbModelSEED/ProbModelSEEDImpl.pm line 116.\n","name":"JSONRPCError","code":-32603,"message":"Can't use an undefined value as an ARRAY reference"},"id":"04267241479828954"}

This should probably return an empty list.  When there are associated FBA studies, the method is working.

**Comment by mmundy42** [comment]
And list_gapfill_solutions(), list_models(), and list_model_edits() have the same problem.  Working on a fix but won't be able to test it until later today or tomorrow.

**Comment by cshenry** [comment]
Thanks Mike! If you check in your fix, I�ll merge it and test locally at least. I�m going to add this condition to the unit tests.

Neal, since Mike has that covered, I�m going to work on the comprehensive model stats function in ProbModelSEED.

BTW, I�m also thinking of switching the media file format in workspace back to JSON instead of the TSV they are now. I�ve just run into a bunch of issues that make me want to roll back that decision before we have any major use of the modeling tools.
It does mean we�ll need an �add_media� and "export_media" function in ProbModelSEED after all. We need an export function for models too. I�ll make sure the export functions have a shock option.

Chris

**Comment by nconrad** [comment]
Cool, thanks!  See https://github.com/ModelSEED/ProbModelSEED/issues/5 for more about the media JSON.

**Comment by mmundy42** [comment]
Pull request #8 has the fix for this problem.

**Comment by mmundy42** [comment]
Closing, pull request #8 was merged to master.
