### ISSUE TITLE
New user issue 

### ISSUE THREAD

**Issue by jplfaria** [ModelSEED/ProbModelSEED#35]
"Something seems to have went wrong. Please try logging out and back in again."

I get this error message when I go to the "My Models" tab when I have no models. We should say instead something like "you have 0 models".
This may be the cause:
{"version":"1.1","error":{"error":"Can't use an undefined value as an ARRAY reference at /disks/p3/deployment/lib/Bio/ModelSEED/ProbModelSEED/ProbModelSEEDImpl.pm line 142.\n","name":"JSONRPCError","code":-32603,"message":"Can't use an undefined value as an ARRAY reference"},"id":"8817047739867121"}
Returned by the server.

**Comment by mmundy42** [comment]
Line 142 is processing the output from listing the objects in the base directory of the workspace for the user.  What userid did you login with?  I'm not sure how the base directory gets created for a new user.

**Comment by jplfaria** [comment]
user ID: jplfaria

Same user name for both RAST and PATRIC accounts, issue persists with both

**Comment by mmundy42** [comment]
I'm assuming that you are using the website at modelseed.theseed.org.  What happens if you click on "All My Files" under the "Advanced" tab (in the blue bar next to your username)?

I'm guessing that when the new folder for the model is created all of the folders in the path are created.

@cshenry, can you confirm that is how the workspace service works.

@nconrad, is there way to check if a user's home folder exists when they login?  And then create the home folder if it does not exist.  The ProbModelSEED service assumes the user's home folder is available in multiple places.

**Comment by samseaver** [comment]
Whether the user's home folder exists prior to the creation of objects or not, I think the problem is simply that the PATRIC Workspace API does not properly handle an empty (home) folder, so this issue should be reported to them directly.

**Comment by nconrad** [comment]
I'm not sure what the issue is exactly, but I agree that this sounds like an accounts/workspace issue.  We shouldn't ship around that kind of logic in client code.

**Comment by mmundy42** [comment]
And I'm not sure how to resolve this issue.  I don't think it is a workspace issue since the workspace is not going to know when a user creates a new account or logs in to ModelSEED for the first time with a RAST or PATRIC account.

We can certainly fix the list_models() method to handle the user not having a home folder.  I think the workspace service ls() method is correctly returning an empty list for an object that does not exist.  I'm just not sure what the design is for getting the home folder created in the PATRIC workspace.
